### ISSUE TITLE
How to add Mermaid and Math plugins?

### ISSUE THREAD

**Issue by figuerom16** [ssssota/svelte-exmarkdown#33]
Firstly I want to say thank you for making this!

I've been building a small interface for your renderer using skeleton for fun.
[markdown](https://mattascale.com/markdown)

The trouble I've been having is adding in more complicated remark/rehype plugins like Mermaid and Math.  Is there an example of how to accomplish this or is it not currently possible?

Thank you for your time.

**Comment by ssssota** [comment]
Thank you for using it as well!


You can render math syntax using [remark-math](https://www.npmjs.com/package/remark-math), [remark-katex](https://www.npmjs.com/package/rehype-katex) and [katex](https://www.npmjs.com/package/katex).
e.g. https://stackblitz.com/edit/svelte-exmarkdown-math?file=src%2Fmath-plugin.ts

And you can render Mermaid like svelte-exmarkdown documents.
Source code is here: https://github.com/ssssota/svelte-exmarkdown/blob/592192e8567f8286d9a5cc4d4fa058dc244d1daa/src/routes/docs/_mermaid/index.ts
Mermaid can only be rendered in the browser, which is why it looks like this :sob:

**Comment by figuerom16** [comment]
Thank you for the quick response.  I see how to configure the math plugin and uploaded the change already!

I think I'm going to skip over mermaid and look for another solution there as I'm not a big fan of how it's rendered and might not be supported anymore.

Thank you!
